JPERF-126: Reduce HTTP load in test
On GitHub Actions, we're getting a ton of failed actions:
```
 com.atlassian.performance.tools.virtualusers.api.EntryPointIT > shouldProduceHttpLoadMetrics FAILED
    java.lang.AssertionError:
    Expecting elements:
    <[ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.055062S, start=2023-09-19T10:23:40.954270Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.013305S, start=2023-09-19T10:23:51.149435Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.005218S, start=2023-09-19T10:24:01.163223Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.001596S, start=2023-09-19T10:24:11.168896Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.001629S, start=2023-09-19T10:24:21.170896Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.001165S, start=2023-09-19T10:24:31.172967Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.005507S, start=2023-09-19T10:24:41.174555Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.003566S, start=2023-09-19T10:24:51.180487Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.002749S, start=2023-09-19T10:25:01.184444Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.000636S, start=2023-09-19T10:25:11.187620Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.004005S, start=2023-09-19T10:25:21.188653Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
        ActionMetric(label=POST search, result=INTERRUPTED, duration=PT10.021932S, start=2023-09-19T10:25:31.193910Z, virtualUser=00e648de-1bd6-4c10-8f97-691b7d9ff871, observation=null),
```

The INTERRUPTED statuses are caused by socket timeouts, probably Jira
doesn't respond in time:
```
2023-09-19T10:10:34,197Z ERROR {} [71a859a9-4964-415c-b6b9-e298380dfa2d] [ThrottlingActionLoop] Failed to run com.atlassian.performance.tools.virtualusers.load.RestSearch@44c1d35e, but we keep running
java.lang.Exception: Failed to run com.atlassian.performance.tools.virtualusers.load.RestSearch@44c1d35e
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop.runWithDiagnostics$virtual_users(ThrottlingActionLoop.kt:74) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop.generateLoad(ThrottlingActionLoop.kt:45) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.LoadTest$run$$inlined$forEach$lambda$1.invoke(LoadTest.kt:53) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.LoadTest$run$$inlined$forEach$lambda$1.invoke(LoadTest.kt:17) ~[main/:?]
	at com.atlassian.performance.tools.jvmtasks.api.TaskTimer.time(TaskTimer.kt:21) ~[jvm-tasks-1.2.3.jar:?]
	at com.atlassian.performance.tools.concurrency.api.TaskContextKt$submitWithLogContext$1.get(TaskContext.kt:24) ~[concurrency-1.1.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
Caused by: java.lang.Exception: Action 'VU Act' INTERRUPTED
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:134) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:84) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop.runWithDiagnostics$virtual_users(ThrottlingActionLoop.kt:67) ~[main/:?]
	... 9 more
Caused by: java.lang.Exception: Action 'POST search' INTERRUPTED
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:134) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:84) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.virtualusers.load.RestSearch.run(HttpLoadProcess.kt:83) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop$runWithDiagnostics$1.invoke(ThrottlingActionLoop.kt:68) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop$runWithDiagnostics$1.invoke(ThrottlingActionLoop.kt:23) ~[main/:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:107) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:84) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop.runWithDiagnostics$virtual_users(ThrottlingActionLoop.kt:67) ~[main/:?]
	... 9 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_362]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_362]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_362]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_362]
	at okio.Okio$2.read(Okio.java:140) ~[okio-1.14.0.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355) ~[okio-1.14.0.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227) ~[okio-1.14.0.jar:?]
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar:?]
	at com.atlassian.performance.tools.virtualusers.load.HttpLoadThreadFactory$prepareThread$http$1.intercept(HttpLoadProcess.kt:38) ~[main/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.11.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.11.0.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.11.0.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.11.0.jar:?]
	at com.atlassian.performance.tools.virtualusers.load.RestSearch$run$1.invoke(HttpLoadProcess.kt:88) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.load.RestSearch$run$1.invoke(HttpLoadProcess.kt:56) ~[main/:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:107) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:84) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.virtualusers.load.RestSearch.run(HttpLoadProcess.kt:83) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop$runWithDiagnostics$1.invoke(ThrottlingActionLoop.kt:68) ~[main/:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop$runWithDiagnostics$1.invoke(ThrottlingActionLoop.kt:23) ~[main/:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:107) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.jiraactions.api.measure.ActionMeter.measure(ActionMeter.kt:84) ~[jira-actions-3.18.1.jar:?]
	at com.atlassian.performance.tools.virtualusers.api.load.ThrottlingActionLoop.runWithDiagnostics$virtual_users(ThrottlingActionLoop.kt:67) ~[main/:?]
	... 9 more
```

But locally, the test passes. Digging in local results, we see that vast
majority of actions is OK, but there are *some* interrupts:
```
▶ cat test-results/*/action-metrics.jpt | grep -c OK
14227

▶ cat test-results/*/action-metrics.jpt | grep -c INTERRUPT
1342
```

So the difference is in the amount of OK/INTERRUPTs.
Hypothesis: my local machine has more computing power than GHA,
so the Jira in Docker has better performance.

GitHub Actions agent:
- https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
- 2-core CPU (x86_64)
- 7 GB of RAM
- 14 GB of SSD space

My work laptop:
- https://www.dell.com/support/manuals/pl-pl/precision-15-5550-laptop/precision_5550_setupspecs/processors?guid=guid-9a5068b5-4242-4265-ab73-ad92da6b2cf6&lang=en-us
- 12-core CPU (x86_64)
- 32 GB of RAM
- 512 GB of SSD space

Therefore, I will reduce the test load to let it pass on GHA.