JPERF-663: Fix multiple IP bindings
It was failing:

```
java.lang.IllegalArgumentException: Array has more than one element.
    at kotlin.collections.ArraysKt___ArraysKt.single(_Arrays.kt:2059)
    at com.atlassian.performance.tools.virtualusers.lib.sshubuntu.SudoSshUbuntuImage.runInStartedContainer(SudoSshUbuntuImage.kt:84)
```
Because two bindings are available: one for IPv4 and one for IPv6,
we need to pick one to connect with.

It's reproducible on GitHub Actions and locally on Linux.